services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: blog_db
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - blog_net

  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - blog_net
    depends_on:
      - mariadb
      - redis

  redis:
    image: redis:latest
    container_name: redis
    environment:
      REDIS_PASSWORD: secret123
    command: redis-server --requirepass secret123
    networks:
      - blog_net

volumes:
  mariadb_data:
    driver: local

networks:
  blog_net:
    driver: bridge